src/profiles/urls.py
from django.urls import path
from .views import profile_view

app_name = "profiles"

urlpatterns = [
    path("", profile_view, name="profile-view"),
]

src/reports/urls.py
from django.urls import path
from .views import (
    create_report_view,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
    UploadTemplateView,
    csv_upload_view,
)

app_name = "reports"

urlpatterns = [
    path("", ReportListView.as_view(), name="report-list"),
    path("create/", create_report_view, name="create-report"),
    path("fileupload/", UploadTemplateView.as_view(), name="file-upload"),
    path("upload/", csv_upload_view, name="upload"),
    path("<pk>/", ReportDetailView.as_view(), name="report-detail"),
    path("<pk>/pdf/", render_pdf_view, name="pdf"),
]

src/reports_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sales.urls", namespace="sales")),
    path("reports/", include("reports.urls", namespace="reports")),
    path("profile/", include("profiles.urls", namespace="profiles")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sales/urls.py
from django.urls import path
from .views import home_view, SalesListView, SaleDetailView

app_name = "sales"

urlpatterns = [
    path("", home_view, name="home"),
    path("sales/", SalesListView.as_view(), name="list"),
    path("sales/<pk>", SaleDetailView.as_view(), name="detail"),
]

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

        <!-- Bootstrap CSS -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
            crossorigin="anonymous"
        />

        <!-- Dropzone JS -->
        <link rel="stylesheet" href="{% static 'dropzone.min.css' %}">
        <script src="{% static 'dropzone.min.js' %}" defer></script>

        <!-- Custome JS and CSS -->
        <link rel="stylesheet" href="{% static 'style.css' %}">
        {% block scripts %}       
        {% endblock scripts %}

        <title>Report App {% block title %} {% endblock title %}</title>
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="container mt-3 mb-3">
            {% block content %}
              
            {% endblock content %}
        </div>

        <!-- Bootstrap JS -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

src/templates/navbar.html
{% url 'sales:home' as path_to_home %}
{% url 'sales:list' as path_to_sales %}
{% url 'reports:report-list' as path_to_reports %}
{% url 'reports:file-upload' as path_to_upload %}
{% url 'profiles:profile-view' as path_to_profile %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">DjangoSales</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" href="{{path_to_home}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_sales %}active{% endif %}" href="{{path_to_sales}}">Sales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_reports %}active{% endif %}" href="{{path_to_reports}}">Reports</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_upload %}active{% endif %}" href="{{path_to_upload}}">Upload CSV</a>
                </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a
                            class="nav-link dropdown-toggle"
                            href="#"
                            id="navbarDropdown"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                        >
                            {{request.user}}
                        </a>
                        <ul
                            class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="navbarDropdown"
                        >
                            <li><a class="dropdown-item" href="{{path_to_profile}}">Profile</a></li>
                            <li>
                                <a class="dropdown-item" href="{% url 'logout'  %}">Logout</a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>