src/reports/urls.py
from django.urls import path
from .views import (
    create_report_view,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
    UploadTemplateView,
    csv_upload_view,
)

app_name = "reports"

urlpatterns = [
    path("", ReportListView.as_view(), name="report-list"),
    path("create/", create_report_view, name="create-report"),
    path("fileupload/", UploadTemplateView.as_view(), name="file-upload"),
    path("upload/", csv_upload_view, name="upload"),
    path("<pk>/", ReportDetailView.as_view(), name="report-detail"),
    path("<pk>/pdf/", render_pdf_view, name="pdf"),
]

src/reports_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sales.urls", namespace="sales")),
    path("reports/", include("reports.urls", namespace="reports")),
    path("profile/", include("profiles.urls", namespace="profiles")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sales/urls.py
from django.urls import path
from .views import home_view, SalesListView, SaleDetailView

app_name = "sales"

urlpatterns = [
    path("", home_view, name="home"),
    path("sales/", SalesListView.as_view(), name="list"),
    path("sales/<pk>", SaleDetailView.as_view(), name="detail"),
]

src/reports/models.py
from django.db import models
from profiles.models import Profile


class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to="reports", blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)


    class Meta:
        ordering = ('-created', )

src/reports/forms.py
from django import forms
from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ("name", "remarks")

src/reports/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.utils.dateparse import parse_date
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from profiles.models import Profile
from django.http import JsonResponse, HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from .utils import get_report_image
from .models import Report
from django.views.generic import ListView, DetailView, TemplateView
from sales.models import Sale, Position, CSV
from products.models import Product
from customers.models import Customer
import csv


@login_required
def create_report_view(request):
    if request.method == "POST":
        name = request.POST.get("name")
        remarks = request.POST.get("remarks")
        image = request.POST.get("image")
        author = Profile.objects.get(user=request.user)

        img = get_report_image(image)

        Report.objects.create(
            name=name, remarks=remarks, image=img, author=author
        )

        return JsonResponse({"message": "Report saved Successfully."})


# def report_view(request):
#     return render(request, "reports/home.html")


class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = "reports/home.html"


class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = "reports/detail.html"


class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = "reports/from_file.html"


@login_required
def csv_upload_view(request):
    print("file is being uploaded")
    if request.method == "POST":
        csv_file_name = request.FILES.get("file").name
        csv_file = request.FILES.get("file")
        obj, created = CSV.objects.get_or_create(file_name=csv_file_name)

        # To restrict the user from uploading the same file
        if created:
            obj.csv_file = csv_file
            obj.save()
            # open csv file
            with open(obj.csv_file.path, "r") as f:
                reader = csv.reader(f)
                reader.__next__()
                for row in reader:
                    transaction_id = row[1]
                    product = row[2]
                    quantity = int(row[3])
                    customer = row[4]
                    created = parse_date(row[5])

                    try:
                        product_obj = Product.objects.get(
                            name__iexact=product
                        )  # iexact is to ignore the case-sensitive
                    except Product.DoesNotExist:
                        product_obj = None

                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(
                            name=customer
                        )
                        salesman_obj = Profile.objects.get(user=request.user)
                        position_obj = Position.objects.create(
                            product=product_obj,
                            quantity=quantity,
                            created=created,
                        )
                        sale_obj, _ = Sale.objects.get_or_create(
                            transaction_id=transaction_id,
                            customer=customer_obj,
                            saleman=salesman_obj,
                            created=created,
                        )
                        sale_obj.positions.add(position_obj)
                        sale_obj.save()
                return JsonResponse({"exists": False})
        else:
            return JsonResponse({"exists": True})
    return HttpResponse()


@login_required
def render_pdf_view(request, pk):
    template_path = "reports/pdf.html"

    obj = get_object_or_404(Report, id=pk)
    context = {"object": obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type="application/pdf")
    # To directly download the file
    # response["Content-Disposition"] = 'attachment; filename="report.pdf"'
    # To display the pdf in the browser
    response["Content-Disposition"] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse("We had some errors <pre>" + html + "</pre>")
    return response

src/reports/templates/reports/detail.html
{% extends "base.html" %}

{% block title %}
  Report Detail
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-10">
      {% if object %}
        <div class="d-flex justify-content-between align-items-center">
          <h3 class="text-muted">Report Detail</h3>
          <a href="{% url 'reports:report-list' %}" class="btn btn-success btn-sm my-3">Go Back</a>
        </div>
        <h2>{{object.name}}</h2>
        <img src="{{object.image.url}}" class="img-fluid mx-auto d-block" alt="{{object.name}}">
        <p class="lead">{{object.remarks}}</p>
        <p><strong>Author: </strong>{{object.author.user.username}}</p>
        <p><strong>Created At: </strong>{{object.created}}</p>
      {% else %}
        <p class="text-center">The page you have been looking for is not here.</p>
      {% endif %}
      
    </div>
  </div>
{% endblock content %}

src/reports/templates/reports/from_file.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
  <script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
  Upload Sales Files
{% endblock title %}

{% block content %}
  <div class="row">
      <div class="col-md-12">
          <h3 class="text-muted my-3">Upload CSV File</h3>
          <div id="alert-box">           
          </div>
          <form id="upload-form" class="dropzone dz mt-3">
            {% csrf_token %}
            <div class="fallback">
              <input name="file" type="file" multiple />
            </div>
          </form>
      </div>
  </div>
{% endblock content %}

src/reports/templates/reports/home.html
{% extends "base.html" %}

{% block title %}
  Django Sales - Reports
{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h2>Sale Reports</h2>
      <div class="row">
        {% for obj in object_list %}
          <div class="col-md-4">
            <div class="card my-3">
              <img src="{{obj.image.url}}" class="card-img-top">
              <div class="card-body">
                <h5 class="card-title">{{obj.name}}</h5>
                <p class="card-text">{{obj.remarks}}</p>
                <a href="{% url 'reports:report-detail' obj.pk %}" class="btn btn-primary btn-sm">View Report</a>
                <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-danger btn-sm">PDF Report</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  
  
{% endblock content %}

src/reports/templates/reports/pdf.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Report - {{object.name}}</title>
        <style>
            .row {
                display: flex;
                justify-content: center;
            }

            .col-md-10 {
                width: 80%;
            }

            .image {
                width: 100%;
                height: auto;
            }
        </style>
    </head>
    <body>
        <div class="row">
            <div class="col-md-10">
                <h2>{{object.name}}</h2>
                <img
                    src="{{object.image.path}}"
                    class="image"
                    alt="{{object.name}}"
                />
                <p><strong>Remarks: </strong>{{object.remarks}}</p>
                <p><strong>Author: </strong>{{object.author.user.username}}</p>
                <p><strong>Created At: </strong>{{object.created}}</p>
            </div>
        </div>
    </body>
</html>